### ISSUE TITLE
when tab in proot, it crash

### ISSUE THREAD

**Issue by XiaoBaiNya** [HardcodedCat/termux-monet#64]
### Problem description

when I tab in proot, termux crashed 
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2023-05-29 16:01:37.690 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2023-05-29 16:01:36.547 UTC`  

**Crash Message**:
```
android.os.SystemVibratorManager cannot be cast to android.os.Vibrator
```

### Stacktrace

```
java.lang.ClassCastException: android.os.SystemVibratorManager cannot be cast to android.os.Vibrator
	at com.termux.app.terminal.TermuxTerminalSessionActivityClient.onBell(TermuxTerminalSessionActivityClient.java:82)
	at com.termux.terminal.TerminalSession.onBell(TerminalSession.java:3)
	at com.termux.terminal.TerminalEmulator.processCodePoint(TerminalEmulator.java:184)
	at com.termux.terminal.TerminalEmulator.processByte(TerminalEmulator.java:126)
	at com.termux.terminal.TerminalSession$MainThreadHandler.handleMessage(TerminalSession.java:28)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**UID**: `10312`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c56,c257,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c56,c257,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**TERMUX_APP_PACKAGE_MANAGER**: `APT`  
**TERMUX_APP_PACKAGE_VARIANT**: `APT_ANDROID_7`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `5.10.101-android12-9-00005-ga829d48e78bd-ab9206161`  
**SDK_INT**: `33`  
**RELEASE**: `13`  
**ID**: `TKQ1.220905.001`  
**DISPLAY**: `TKQ1.220905.001 test-keys`  
**INCREMENTAL**: `V14.0.24.0.TMNCNXM`  
**SECURITY_PATCH**: `2023-04-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  
**MAX_PHANTOM_PROCESSES**: - (*需要 `DUMP` 和 `PACKAGE_USAGE_STATS` 权限*)  
**MONITOR_PHANTOM_PROCS**: `false`  
**DEVICE_CONFIG_SYNC_DISABLED**: -  

### Hardware

**MANUFACTURER**: `Xiaomi`  
**BRAND**: `Redmi`  
**MODEL**: `23013RK75C`  
**PRODUCT**: `mondrian`  
**BOARD**: `taro`  
**HARDWARE**: `qcom`  
**DEVICE**: `mondrian`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

proot-distro login archlinux --user mayu --shared-tmp
cd <tab>

### What is the expected behavior?

cd <tab>
Desktop/  downloads/  Music/  storage/

### System information

* Termux Monet version:0.118.0-32
* Is Nightly or Stable?:Stable
* Android OS version:13
* Device model:redmi k60
*

**Comment by HardcodedCat** [comment]
Fixed in https://github.com/HardcodedCat/termux-monet/pull/66. Check out the latest hotfix release
