### ISSUE TITLE
Not BUG help required pantom process killer can't enable via adb

### ISSUE THREAD

**Issue by Saikatsaha1996** [HardcodedCat/termux-monet#71]
### Problem description

Unable to complete pantom process killer..

### Steps to reproduce the behavior.

```
C:\Windows\system32>adb shell settings put global settings_enable_monitor_phantom_procs false

Exception occurred while executing 'put':
java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2562)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1562)
        at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1516)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:495)
        at android.content.ContentProvider.call(ContentProvider.java:2511)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:525)
        at com.android.providers.settings.SettingsService$MyShellCommand.putForUser(SettingsService.java:384)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:280)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
        at android.os.Binder.shellCommand(Binder.java:1073)
        at android.os.Binder.onTransact(Binder.java:901)
        at android.os.Binder.execTransactInternal(Binder.java:1331)
        at android.os.Binder.execTransact(Binder.java:1268)
```

### System information

* Termux Monet version:
* Is Nightly or Stable?:
* Android OS version:
* Device model:
*
0.118 version application
Android 13
Realme GT 2

**Comment by Saikatsaha1996** [comment]
Solved..
